import type { Metadata } from "next";
import "./styles/globals.css";
import { titleFont } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={titleFont.className}>{children}</body>
    </html>
  );
}
